version: "3.9"

networks:
  dem:

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - dem
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - dem
    depends_on:
      - postgres

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    volumes:
      - .:/DOCK
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/postgresDB"
    networks:
      - dem
    depends_on:
      - postgres
    


volumes:
  postgres_data:
